### ISSUE TITLE
Uploading the code?

### ISSUE THREAD

**Issue by jenvigo** [ggelashvili/learnphptherightway-outline#1]
First of all, thanks for the videos, they are really helping me. 

I am watching the one of DBAL but the last part of the video does a quick refactor of the DB and Connection class that it's a bit hard to understand without seeing the initial structure for a few minutes.
This is why I would suggest you upload the code here so we can clone it and play with it to fully grasp the concepts.

**Comment by ggelashvili** [comment]
Hey, thank you. Most videos have source on GitHub. Check the description of the video, there should be a link to the GitHub repo with proper branch that contains the changes for that video.

**Comment by jenvigo** [comment]
Oh. My bad, the description popups in the right sidebar and I didn't notice the link. Thanks for the hint.

**Comment by ggelashvili** [comment]
No problem
